name: wolt_responsive_layout_grid
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/woltapp/wolt-responsive-layout-grid

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true

dev_dependencies:
  lints: ^2.0.1
  # Flutter test tools
  flutter_test:
    sdk: flutter
  # Test lib.
  test:
